FROM ana-api:latest

USER root
RUN apt-get update && apt-get install -y make postgresql-client git && rm -rf /var/lib/apt/lists/*

# Instala o projeto com todas as dependências (incluindo as de dev como DVC)
# E garante que o Airflow seja instalado com as restrições oficiais
RUN pip install --no-cache-dir "apache-airflow[postgres]==2.9.0" \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.0/constraints-3.10.txt" && \
    pip install --no-cache-dir -e ".[dev]"

# Configurações de ambiente para o Airflow
ENV AIRFLOW_HOME=/app/airflow
ENV AIRFLOW__CORE__LOAD_EXAMPLES=False
ENV AIRFLOW__CORE__EXECUTOR=LocalExecutor

# O entrypoint original da ana-api pode não ser adequado para o Airflow
# Vamos usar o comando do airflow diretamente no docker-compose
