stages:
  prepare_data:
    cmd: PYTHONPATH=. ambi/bin/python db_lite/create_db.py && PYTHONPATH=. ambi/bin/python db_lite/data_base.py
    deps:
      - db_lite/create_db.py
      - db_lite/data_base.py
    outs:
      - db_lite/meu_banco_de_dados.db

  train:
    cmd: PYTHONPATH=. ambi/bin/python src/models/train.py
    deps:
      - db_lite/meu_banco_de_dados.db
      - src/models/train.py
    outs:
      - src/models/modelo_glosa.skops
      - src/models/features_modelo.json

  inference:
    cmd: PYTHONPATH=. ambi/bin/python src/models/insert_db_model.py
    deps:
      - src/models/modelo_glosa.skops
      - src/models/features_modelo.json
      - src/models/insert_db_model.py
      - db_lite/meu_banco_de_dados.db

  evaluate:
    cmd: PYTHONPATH=. ambi/bin/python evaluation/ragas_eval.py
    deps:
      - evaluation/ragas_eval.py
      - data/golden_set/golden_set.json
      - db_lite/meu_banco_de_dados.db

